### ISSUE TITLE
there is maybe something wrong in my train.py

### ISSUE THREAD

**Issue by xsmxsm** [kaonashi-tyc/zi2zi#32]
@kaonashi-tyc 

python package1.py --dir=dir2 --save_dir=save_dir2 --split_ratio=0
img dir2/0_0000.jpg 0
img dir2/0_0001.jpg 0
img dir2/0_0002.jpg 0
img dir2/0_0003.jpg 0
img dir2/0_0004.jpg 0
img dir2/0_0005.jpg 0
img dir2/0_0006.jpg 0
img dir2/0_0007.jpg 0
img dir2/0_0008.jpg 0
img dir2/0_0009.jpg 0
img dir2/0_0010.jpg 0
......
img dir2/0_2942.jpg 0
img dir2/0_2943.jpg 0
img dir2/0_2944.jpg 0
img dir2/0_2945.jpg 0
img dir2/0_2946.jpg 0
img dir2/0_2947.jpg 0
img dir2/0_2948.jpg 0
img dir2/0_2949.jpg 0
img dir2/0_2950.jpg 0
img dir2/0_2951.jpg 0

python train.py --experiment_dir=experiment --experiment_id=0 --batch_size=24 --lr=0.001 --epoch=10 --sample_steps=123  --schedule=20 --L1_penalty=100 --Lconst_penalty=15
2017-10-09 19:01:32.313597: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-09 19:01:32.313626: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-09 19:01:32.313631: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-09 19:01:32.313636: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-09 19:01:32.313640: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-10-09 19:01:32.537983: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.582
pciBusID 0000:02:00.0
Total memory: 10.91GiB
Free memory: 10.18GiB
2017-10-09 19:01:32.538014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2017-10-09 19:01:32.538020: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2017-10-09 19:01:32.538027: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0)
processed 1000 examples
processed 2000 examples
unpickled total 2952 examples
unpickled total 0 examples
train examples -> 2952, val examples -> 0
fail to restore model experiment/checkpoint/experiment_0_batch_24
Epoch: [ 0], [   0/ 123] time: 6.0433, d_loss: 10.14546, g_loss: 274.66415, category_loss: 0.00000, cheat_loss: 173.93898, const_loss: 7.20869, l1_loss: 93.51649, tv_loss: 0.00000
Epoch: [ 0], [   1/ 123] time: 8.1327, d_loss: 146.35306, g_loss: 78.34413, category_loss: 0.00000, cheat_loss: 0.00000, const_loss: 0.12824, l1_loss: 78.21589, tv_loss: 0.00000
Epoch: [ 0], [   2/ 123] time: 10.2258, d_loss: 181.37769, g_loss: 152.27695, category_loss: 0.00000, cheat_loss: 97.29399, const_loss: 0.06894, l1_loss: 54.91401, tv_loss: 0.00000
Epoch: [ 0], [   3/ 123] time: 12.3139, d_loss: 60.48555, g_loss: 35.58843, category_loss: 0.00000, cheat_loss: 0.00000, const_loss: 0.04017, l1_loss: 35.54825, tv_loss: 0.00000
Epoch: [ 0], [   4/ 123] time: 14.4027, d_loss: 68.51615, g_loss: 75.03025, category_loss: 0.00000, cheat_loss: 49.46065, const_loss: 0.06694, l1_loss: 25.50266, tv_loss: 0.00000
Epoch: [ 0], [   5/ 123] time: 16.5009, d_loss: 16.37053, g_loss: 24.69693, category_loss: 0.00000, cheat_loss: 3.03605, const_loss: 0.07840, l1_loss: 21.58248, tv_loss: 0.00000
Epoch: [ 0], [   6/ 123] time: 18.5991, d_loss: 14.45806, g_loss: 92.51143, category_loss: 0.00000, cheat_loss: 73.25694, const_loss: 0.09051, l1_loss: 19.16398, tv_loss: 0.00000
Epoch: [ 0], [   7/ 123] time: 20.6916, d_loss: 39.45554, g_loss: 19.35016, category_loss: 0.00000, cheat_loss: 0.27510, const_loss: 0.23808, l1_loss: 18.83698, tv_loss: 0.00000
Epoch: [ 0], [   8/ 123] time: 22.7883, d_loss: 47.10860, g_loss: 71.88419, category_loss: 0.00000, cheat_loss: 50.56374, const_loss: 0.10448, l1_loss: 21.21597, tv_loss: 0.00000
Epoch: [ 0], [   9/ 123] time: 24.8894, d_loss: 34.83733, g_loss: 58.39854, category_loss: 0.00000, cheat_loss: 30.93460, const_loss: 0.70017, l1_loss: 26.76377, tv_loss: 0.00000
Epoch: [ 0], [  10/ 123] time: 26.9899, d_loss: 103.12030, g_loss: 47.40792, category_loss: 0.00000, cheat_loss: 2.60304, const_loss: 19.21144, l1_loss: 25.59344, tv_loss: 0.00000
......
Epoch: [ 0], [ 121/ 123] time: 263.4440, d_loss: 33.96601, g_loss: 20.80124, category_loss: 0.00000, cheat_loss: 0.01192, const_loss: 0.69635, l1_loss: 20.09298, tv_loss: 0.00000
Epoch: [ 0], [ 122/ 123] time: 265.5618, d_loss: 24.81020, g_loss: 62.80609, category_loss: 0.00000, cheat_loss: 42.07758, const_loss: 0.16414, l1_loss: 20.56438, tv_loss: 0.00i000
^CTraceback (most recent call last):
  File "train.py", line 62, in <module>
    tf.app.run()
  File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 58, in main
    sample_steps=args.sample_steps, checkpoint_steps=args.checkpoint_steps)
  File "/home/customer/zi2zi-master/model/unet.py", line 539, in train
    self.validate_model(val_batch_iter, ei, counter)
  File "/home/customer/zi2zi-master/model/unet.py", line 325, in validate_model
    labels, images = next(val_iter)
  File "/home/customer/zi2zi-master/model/dataset.py", line 101, in get_val_iter
    val_batch_iter = get_batch_iter(val_examples, batch_size, augment=False)
  File "/home/customer/zi2zi-master/model/dataset.py", line 39, in get_batch_iter
    def process(img):
KeyboardInterrupt

in the train.py, it fail to restore model experiment/checkpoint/experiment_0_batch_24, what is wrong with it?

**Comment by Henry658** [comment]
Did you solved it ?
how?
