### ISSUE TITLE
infer  error when use my model

### ISSUE THREAD

**Issue by xsmxsm** [kaonashi-tyc/zi2zi#34]
@kaonashi-tyc 

i trained my model use 
1. python font2img.py --src_font=simsun.ttf --dst_font=钟齐山文丰手写体.ttf --charset=top_3000_simplified.txt --sample_count=3000 --sample_dir=dir3 --label=0 --filter=1 --shuffle=1

2. python package.py --dir=dir3 --save_dir=save_dir3 --split_ratio=0.1

3. python train.py --experiment_dir=experiment --experiment_id=0 --batch_size=50 --lr=0.001 --epoch=100 --sample_steps=60 --schedule=20 --L1_penalty=100 --Lconst_penalty=15

in the experiment/checkpoint/experiment_0_batch_50 dir , why it has  "checkpoint" ,"unet.model-4500.data-00000-of-00001","unet.model-4500.index", "unet.model-4500.meta", "unet.model-5000.data-00000-of-00001", "unet.model-5000.index", "unet.model-5000.meta", "unet.model-5500.data-00000-of-00001", "unet.model-5500.index", "unet.model-5500.meta", 10 files? 

I download your model ,it only has 4 files.

Is there any error in my train? My tensorflow is 1.3.0
(训练结果怎么有那么多文件？我下载的您的模型里面只有四个文件)

另一个问题：
我在使用自己训练的模型进行infer时，出现以下错误：

python infer.py --model_dir=font3 --batch_size=50 --source_obj=save_dir1/train.obj --embedding_ids=0 --save_dir=save_dir1
2017-10-13 08:27:21.597033: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-13 08:27:21.597060: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-13 08:27:21.597065: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-13 08:27:21.597069: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-13 08:27:21.597074: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-10-13 08:27:21.870330: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.582
pciBusID 0000:02:00.0
Total memory: 10.91GiB
Free memory: 10.39GiB
2017-10-13 08:27:21.870368: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2017-10-13 08:27:21.870376: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2017-10-13 08:27:21.870386: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0)
unpickled total 9 examples
examples -> 9
2017-10-13 08:27:23.749874: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [40,1,1,128] rhs shape= [1,1,1,128]
	 [[Node: save/Assign_6 = Assign[T=DT_FLOAT, _class=["loc:@embedding/E"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](embedding/E, save/RestoreV2_6/_189)]]
2017-10-13 08:27:23.750613: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [40,1,1,128] rhs shape= [1,1,1,128]
	 [[Node: save/Assign_6 = Assign[T=DT_FLOAT, _class=["loc:@embedding/E"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](embedding/E, save/RestoreV2_6/_189)]]
Traceback (most recent call last):
  File "infer.py", line 67, in <module>
    tf.app.run()
  File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "infer.py", line 47, in main
    save_dir=args.save_dir)
  File "/home/customer/zi2zi-master/model/unet.py", line 360, in infer
    self.restore_model(saver, model_dir)
  File "/home/customer/zi2zi-master/model/unet.py", line 305, in restore_model
    saver.restore(self.sess, ckpt.model_checkpoint_path)
  File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [40,1,1,128] rhs shape= [1,1,1,128]
	 [[Node: save/Assign_6 = Assign[T=DT_FLOAT, _class=["loc:@embedding/E"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](embedding/E, save/RestoreV2_6/_189)]]

Caused by op u'save/Assign_6', defined at:
  File "infer.py", line 67, in <module>
    tf.app.run()
  File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "infer.py", line 47, in main
    save_dir=args.save_dir)
  File "/home/customer/zi2zi-master/model/unet.py", line 359, in infer
    saver = tf.train.Saver(var_list=self.retrieve_generator_vars())
  File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1140, in __init__
    self.build()
  File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1172, in build
    filename=self._filename)
  File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 688, in build
    restore_sequentially, reshape)
  File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 274, in assign
    validate_shape=validate_shape)
  File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 43, in assign
    use_locking=use_locking, name=name)
  File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [40,1,1,128] rhs shape= [1,1,1,128]
	 [[Node: save/Assign_6 = Assign[T=DT_FLOAT, _class=["loc:@embedding/E"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](embedding/E, save/RestoreV2_6/_189)]]

这是tensorflow的版本问题吗？但是我在使用您的模型进行infer时是没有这种错误的。

**Comment by wmonica** [comment]
Have you ever solved this problem? How you did this?

**Comment by xsmxsm** [comment]
@wmonica 
yes, I have soveled it. Because there are some errors in my training model, so it cant't infer success.

the error is lhs shape= [40,1,1,128] rhs shape= [1,1,1,128]
in train.py line  20, "parser.add_argument('--embedding_num', dest='embedding_num', type=int, default=40,  help="number for distinct embeddings") " ;   embedding_num=40, so I change  zi2zi-master/model/unet.py  line 27, embedding_num=40.
and then train my model , my model can infer successfully.

**Comment by wmonica** [comment]
Thank you very much for your letter.
My errors are:
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [6,1,1,128] rhs shape= [40,1,1,128]
 [[Node: save/Assign_6 = Assign[T=DT_FLOAT, _class=["loc:@embedding/E"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](embedding/E, save/RestoreV2_6/_189)]]
I have trained my own model for 6 classes. There is a little difference between our error information.  How you obtained [1,1,1,128], I need to change this value.


Xueping Wang
wangxueping_01@sina.com
 
From: xsmxsm
Date: 2017-11-08 08:49
To: kaonashi-tyc/zi2zi
CC: wmonica; Mention
Subject: Re: [kaonashi-tyc/zi2zi] infer error when use my model (#34)
@wmonica
yes, I have soveled it. Because there are some errors in my training model, so it cant't infer success.
the error is lhs shape= [40,1,1,128] rhs shape= [1,1,1,128]
in train.py line 20, "parser.add_argument('--embedding_num', dest='embedding_num', type=int, default=40, help="number for distinct embeddings") " ; embedding_num=40, so I change zi2zi-master/model/unet.py line 27, embedding_num=40.
and then train my model , my model can infer successfully.

**Comment by wmonica** [comment]
Thank you very much for your reply.
My errors are:
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [6,1,1,128] rhs shape= [40,1,1,128]
	 [[Node: save/Assign_6 = Assign[T=DT_FLOAT, _class=["loc:@embedding/E"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](embedding/E, save/RestoreV2_6/_189)]]
I have trained my own model for 6 classes. There is a little difference between our error information.  How you obtained [1,1,1,128], I need to change this value.

**Comment by xsmxsm** [comment]
@wmonica 

you have to change lhs shape=rhs shape,then the error can sovel.
maybe you should change your embedding_num=40(or other number), same in train.py and unet.py
you should try it, because I am not very sure it may sovel your problem.

**Comment by wmonica** [comment]
Thank you for your help. 
 
From: xsmxsm
Date: 2017-11-08 09:07
To: kaonashi-tyc/zi2zi
CC: wmonica; Mention
Subject: Re: [kaonashi-tyc/zi2zi] infer error when use my model (#34)
@wmonica
you have to change lhs shape=rhs shape,then the error can sovel.
maybe you should change your embedding_num=40(or other number), same in train.py and unet.py
you should try it, because I am not very sure it may sovel your problem.

**Comment by wmonica** [comment]
@xsmxsm Thank you for your help.

**Comment by ruiniao** [comment]
I got an error: 
"infer.py: error: unrecognized arguments: ./result/train.obj"

What is the problem?

**Comment by Instantnoodles-madman** [comment]
> @kaonashi-tyc
> 
> i trained my model use
> 
> 1. python font2img.py --src_font=simsun.ttf --dst_font=钟齐山文丰手写体.ttf --charset=top_3000_simplified.txt --sample_count=3000 --sample_dir=dir3 --label=0 --filter=1 --shuffle=1
> 2. python package.py --dir=dir3 --save_dir=save_dir3 --split_ratio=0.1
> 3. python train.py --experiment_dir=experiment --experiment_id=0 --batch_size=50 --lr=0.001 --epoch=100 --sample_steps=60 --schedule=20 --L1_penalty=100 --Lconst_penalty=15
> 
> in the experiment/checkpoint/experiment_0_batch_50 dir , why it has "checkpoint" ,"unet.model-4500.data-00000-of-00001","unet.model-4500.index", "unet.model-4500.meta", "unet.model-5000.data-00000-of-00001", "unet.model-5000.index", "unet.model-5000.meta", "unet.model-5500.data-00000-of-00001", "unet.model-5500.index", "unet.model-5500.meta", 10 files?
> 
> I download your model ,it only has 4 files.
> 
> Is there any error in my train? My tensorflow is 1.3.0
> (训练结果怎么有那么多文件？我下载的您的模型里面只有四个文件)
> 
> 另一个问题：
> 我在使用自己训练的模型进行infer时，出现以下错误：
> 
> python infer.py --model_dir=font3 --batch_size=50 --source_obj=save_dir1/train.obj --embedding_ids=0 --save_dir=save_dir1
> 2017-10-13 08:27:21.597033: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
> 2017-10-13 08:27:21.597060: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
> 2017-10-13 08:27:21.597065: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
> 2017-10-13 08:27:21.597069: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
> 2017-10-13 08:27:21.597074: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
> 2017-10-13 08:27:21.870330: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties:
> name: GeForce GTX 1080 Ti
> major: 6 minor: 1 memoryClockRate (GHz) 1.582
> pciBusID 0000:02:00.0
> Total memory: 10.91GiB
> Free memory: 10.39GiB
> 2017-10-13 08:27:21.870368: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0
> 2017-10-13 08:27:21.870376: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0: Y
> 2017-10-13 08:27:21.870386: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0)
> unpickled total 9 examples
> examples -> 9
> 2017-10-13 08:27:23.749874: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [40,1,1,128] rhs shape= [1,1,1,128]
> [[Node: save/Assign_6 = Assign[T=DT_FLOAT, _class=["loc:@embedding/E"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](embedding/E, save/RestoreV2_6/_189)]]
> 2017-10-13 08:27:23.750613: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [40,1,1,128] rhs shape= [1,1,1,128]
> [[Node: save/Assign_6 = Assign[T=DT_FLOAT, _class=["loc:@embedding/E"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](embedding/E, save/RestoreV2_6/_189)]]
> Traceback (most recent call last):
> File "infer.py", line 67, in
> tf.app.run()
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
> _sys.exit(main(_sys.argv[:1] + flags_passthrough))
> File "infer.py", line 47, in main
> save_dir=args.save_dir)
> File "/home/customer/zi2zi-master/model/unet.py", line 360, in infer
> self.restore_model(saver, model_dir)
> File "/home/customer/zi2zi-master/model/unet.py", line 305, in restore_model
> saver.restore(self.sess, ckpt.model_checkpoint_path)
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1560, in restore
> {self.saver_def.filename_tensor_name: save_path})
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
> run_metadata_ptr)
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
> feed_dict_tensor, options, run_metadata)
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
> options, run_metadata)
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
> raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [40,1,1,128] rhs shape= [1,1,1,128]
> [[Node: save/Assign_6 = Assign[T=DT_FLOAT, _class=["loc:@embedding/E"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](embedding/E, save/RestoreV2_6/_189)]]
> 
> Caused by op u'save/Assign_6', defined at:
> File "infer.py", line 67, in
> tf.app.run()
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
> _sys.exit(main(_sys.argv[:1] + flags_passthrough))
> File "infer.py", line 47, in main
> save_dir=args.save_dir)
> File "/home/customer/zi2zi-master/model/unet.py", line 359, in infer
> saver = tf.train.Saver(var_list=self.retrieve_generator_vars())
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1140, in **init**
> self.build()
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1172, in build
> filename=self._filename)
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 688, in build
> restore_sequentially, reshape)
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
> assign_ops.append(saveable.restore(tensors, shapes))
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 155, in restore
> self.op.get_shape().is_fully_defined())
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 274, in assign
> validate_shape=validate_shape)
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 43, in assign
> use_locking=use_locking, name=name)
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
> op_def=op_def)
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
> original_op=self._default_original_op, op_def=op_def)
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in **init**
> self._traceback = self._graph._extract_stack() # pylint: disable=protected-access
> 
> InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [40,1,1,128] rhs shape= [1,1,1,128]
> [[Node: save/Assign_6 = Assign[T=DT_FLOAT, _class=["loc:@embedding/E"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](embedding/E, save/RestoreV2_6/_189)]]
> 
> 这是tensorflow的版本问题吗？但是我在使用您的模型进行infer时是没有这种错误的。
请问再进行Python infer.py 时 其中的source_obj参数应该是什么？图片吗？

**Comment by lionel-daydayup** [comment]
> @kaonashi-tyc
> 
> i trained my model use
> 
> 1. python font2img.py --src_font=simsun.ttf --dst_font=钟齐山文丰手写体.ttf --charset=top_3000_simplified.txt --sample_count=3000 --sample_dir=dir3 --label=0 --filter=1 --shuffle=1
> 2. python package.py --dir=dir3 --save_dir=save_dir3 --split_ratio=0.1
> 3. python train.py --experiment_dir=experiment --experiment_id=0 --batch_size=50 --lr=0.001 --epoch=100 --sample_steps=60 --schedule=20 --L1_penalty=100 --Lconst_penalty=15
> 
> in the experiment/checkpoint/experiment_0_batch_50 dir , why it has "checkpoint" ,"unet.model-4500.data-00000-of-00001","unet.model-4500.index", "unet.model-4500.meta", "unet.model-5000.data-00000-of-00001", "unet.model-5000.index", "unet.model-5000.meta", "unet.model-5500.data-00000-of-00001", "unet.model-5500.index", "unet.model-5500.meta", 10 files?
> 
> I download your model ,it only has 4 files.
> 
> Is there any error in my train? My tensorflow is 1.3.0
> (训练结果怎么有那么多文件？我下载的您的模型里面只有四个文件)
> 
> 另一个问题：
> 我在使用自己训练的模型进行infer时，出现以下错误：
> 
> python infer.py --model_dir=font3 --batch_size=50 --source_obj=save_dir1/train.obj --embedding_ids=0 --save_dir=save_dir1
> 2017-10-13 08:27:21.597033: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
> 2017-10-13 08:27:21.597060: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
> 2017-10-13 08:27:21.597065: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
> 2017-10-13 08:27:21.597069: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
> 2017-10-13 08:27:21.597074: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
> 2017-10-13 08:27:21.870330: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties:
> name: GeForce GTX 1080 Ti
> major: 6 minor: 1 memoryClockRate (GHz) 1.582
> pciBusID 0000:02:00.0
> Total memory: 10.91GiB
> Free memory: 10.39GiB
> 2017-10-13 08:27:21.870368: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0
> 2017-10-13 08:27:21.870376: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0: Y
> 2017-10-13 08:27:21.870386: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0)
> unpickled total 9 examples
> examples -> 9
> 2017-10-13 08:27:23.749874: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [40,1,1,128] rhs shape= [1,1,1,128]
> [[Node: save/Assign_6 = Assign[T=DT_FLOAT, _class=["loc:@embedding/E"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](embedding/E, save/RestoreV2_6/_189)]]
> 2017-10-13 08:27:23.750613: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [40,1,1,128] rhs shape= [1,1,1,128]
> [[Node: save/Assign_6 = Assign[T=DT_FLOAT, _class=["loc:@embedding/E"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](embedding/E, save/RestoreV2_6/_189)]]
> Traceback (most recent call last):
> File "infer.py", line 67, in 
> tf.app.run()
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
> _sys.exit(main(_sys.argv[:1] + flags_passthrough))
> File "infer.py", line 47, in main
> save_dir=args.save_dir)
> File "/home/customer/zi2zi-master/model/unet.py", line 360, in infer
> self.restore_model(saver, model_dir)
> File "/home/customer/zi2zi-master/model/unet.py", line 305, in restore_model
> saver.restore(self.sess, ckpt.model_checkpoint_path)
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1560, in restore
> {self.saver_def.filename_tensor_name: save_path})
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
> run_metadata_ptr)
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
> feed_dict_tensor, options, run_metadata)
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
> options, run_metadata)
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
> raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [40,1,1,128] rhs shape= [1,1,1,128]
> [[Node: save/Assign_6 = Assign[T=DT_FLOAT, _class=["loc:@embedding/E"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](embedding/E, save/RestoreV2_6/_189)]]
> 
> Caused by op u'save/Assign_6', defined at:
> File "infer.py", line 67, in 
> tf.app.run()
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
> _sys.exit(main(_sys.argv[:1] + flags_passthrough))
> File "infer.py", line 47, in main
> save_dir=args.save_dir)
> File "/home/customer/zi2zi-master/model/unet.py", line 359, in infer
> saver = tf.train.Saver(var_list=self.retrieve_generator_vars())
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1140, in **init**
> self.build()
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1172, in build
> filename=self._filename)
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 688, in build
> restore_sequentially, reshape)
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
> assign_ops.append(saveable.restore(tensors, shapes))
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 155, in restore
> self.op.get_shape().is_fully_defined())
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 274, in assign
> validate_shape=validate_shape)
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 43, in assign
> use_locking=use_locking, name=name)
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
> op_def=op_def)
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
> original_op=self._default_original_op, op_def=op_def)
> File "/opt/software/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in **init**
> self._traceback = self._graph._extract_stack() # pylint: disable=protected-access
> 
> InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [40,1,1,128] rhs shape= [1,1,1,128]
> [[Node: save/Assign_6 = Assign[T=DT_FLOAT, _class=["loc:@embedding/E"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](embedding/E, save/RestoreV2_6/_189)]]
> 
> 这是tensorflow的版本问题吗？但是我在使用您的模型进行infer时是没有这种错误的。

可以告诉我你是怎么得到这个文件的嘛top_3000_simplified.tx，我这边是直接把rewrite项目里面的下载下来，但是报错了说Traceback (most recent call last):
  File "C:/Users/dell/Desktop/zi2zi-master/font2img.py", line 116, in <module>
    charset = [c for c in open(args.charset).readline()[:-1].decode("utf-8")]
UnicodeDecodeError: 'gbk' codec can't decode byte 0x84 in position 2: illegal multibyte sequence
