### ISSUE TITLE
imageio errors

### ISSUE THREAD

**Issue by sellinaxmj** [kaonashi-tyc/zi2zi#43]
when i tried to train,some errors arised.thanks for your help.
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    from model.unet import UNet
  File "/mnt/data/zi2zi-master/model/unet.py", line 12, in <module>
    from .dataset import TrainDataProvider, InjectDataProvider, NeverEndingLoopingProvider
  File "/mnt/data/zi2zi-master/model/dataset.py", line 8, in <module>
    from .utils import pad_seq, bytes_to_file, \
  File "/mnt/data/zi2zi-master/model/utils.py", line 8, in <module>
    import imageio
ImportError: No module named imageio

**Comment by xsmxsm** [comment]
@sellinaxmj   你的环境没有配置好，缺少imageio模块，先安装好imageio再训练

**Comment by LinkWoong** [comment]
pip install imageio
