### ISSUE TITLE
infer.py question

### ISSUE THREAD

**Issue by ouguozhen** [kaonashi-tyc/zi2zi#51]
你好,有几个问题,希望能解答一下.
在测试的时候,输入图片的大小是固定的吗(我直接用fonts27测试的)? 并且如果一张图片中包含了多个文字的话,效果就会非常差,是不是一张图片包含的文字数目也有限制呢?

**Comment by lionel-daydayup** [comment]
> 你好,有几个问题,希望能解答一下.
> 在测试的时候,输入图片的大小是固定的吗(我直接用fonts27测试的)? 并且如果一张图片中包含了多个文字的话,效果就会非常差,是不是一张图片包含的文字数目也有限制呢?

您好，请问您是如何使用font27的呢，我这边使用的时候会报错。我把名字fonts27文件名改成了experiment_1_batch_50。然后就会报错。请问我应该如何使用font27呢，可以告知一下吗INFO:tensorflow:Restoring parameters from pickled/checkpoint/experiment_1_batch_50/gen_model-0
I0818 13:58:27.369446 140300161460032 saver.py:1284] Restoring parameters from pickled/checkpoint/experiment_1_batch_50/gen_model-0
2020-08-18 13:58:27.792302: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key beta1_power not found in checkpoint
Traceback (most recent call last):
  File "/usr/local/python/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/python/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/python/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key beta1_power not found in checkpoint
	 [[{{node save/RestoreV2}}]]
  (1) Not found: Key beta1_power not found in checkpoint
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_149]]
